### ISSUE TITLE
[Bug]: Check if refinement level is greater than kmax

### ISSUE THREAD

**Issue by Overmeen** [nens/threedi-modelchecker#198] opened 2022-07-18 13:20 UTC
### Contact Details

stijn.overmeen@nelen-schuurmans.nl

### Complexity

easy

### Priority

low prio

### What happened?

A refinement level (v2_grid_refinements) greater than kmax (v2_global_settings) is not possible, however not checked yet.

In such a case a model is made. However, simulations crash from start.

See also, servicedesk ticket: 2207 0102 'starting up simulation' - berekening voor Groningen.

### How to Reproduce?

Open calculater.
Press 1,
Press +,
Press 1,
Press =

### What did you expect and what was the actual result?

I expected 2 but the calculator returned 3

### Add screenshots, video's etc

The maximum size for files is 25MB and the maximum size for images is 10MB.

### Additional info

Anything else you would like to share?

**Comment by caspervdw** [comment] 2022-10-13 07:40
Duplicate of #211

**Closed by caspervdw** 2022-10-13 07:40 UTC
Labels: bug
