### ISSUE TITLE
Check if settings records are used

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-modelchecker#236] opened 2022-11-25 21:02 UTC
If e.g. a record in the v2_simple_infiltration table exists but is not referenced from v2_global_settings, please show this. I think it should be INFO level, because it _may_ be a perfectly valid and intended thing to do

**Comment by Jonasvsl** [comment] 2023-01-19 08:11
similar to? https://app.zenhub.com/workspaces/nelen-en-schuurmans-overview-628211daedba7600185a165a/issues/gh/nens/threedi-modelchecker/168

**Comment by caspervdw** [comment] 2023-02-08 08:45
Duplicate of #168

**Closed by caspervdw** 2023-02-08 08:45 UTC
