### ISSUE TITLE
Projection: epsg/proj consistency check

### ISSUE THREAD

**Issue by jpprins1** [nens/threedi-modelchecker#69] opened 2021-08-31 12:30 UTC
- [ ] Should be the same in global settings and rasters.
- [ ] epsg_code in global settings should be valid/usable epsg_code

**Comment by caspervdw** [comment] 2021-09-30 17:37
This is technically challanging; we need to download the complete DEM into the model checker in order to do the check.

Maybe it is best to ignore epsg_code if a DEM is provided? It is easy to add a warning if that is the case (and an error if both epsg_code and dem_file) are absent. @Jonasvsl

**Comment by Jonasvsl** [comment] 2021-10-01 08:00
are you sure you need to download a tif for this check? I remember seeing examples where gdal was able to connect to online data.  i would expect that to be possible especially with cogs

**Comment by caspervdw** [comment] 2021-12-21 15:36
I think we must leave this out of the Klondike release, it is too challenging to fix before.

**Comment by caspervdw** [comment] 2022-11-03 09:50
Currently the epsg_code is ignored whenever there is a DEM provided. I think that is a workable solution.

When there is a DEM, the only reason to include the epsg_code inside the modelchecker is to be able to do spatial checks. There is currently no validation of the epsg code against the DEM. We could add that, and skip it if there is no DEM present.

**Comment by caspervdw** [comment] 2022-11-03 14:50
Could be solved by sending the epsg code from the API into the modelchecker worker ((https://github.com/nens/threedi-api/issues/1789)

**Comment by caspervdw** [comment] 2023-02-08 08:32
I think that this could be solved now as part of the new raster checks!

**Comment by caspervdw** [comment] 2023-02-08 08:41
Duplicate of https://github.com/nens/threedi-modelchecker/issues/228

**Closed by caspervdw** 2023-02-08 08:41 UTC
