### ISSUE TITLE
[3Di]: schematisation checker should check for unique entries in the aggregation values

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-modelchecker#121] opened 2021-12-03 11:33 UTC
### Incident Type

Error

### 3Di component

Model repositories / inpy

### What happened?

I typed the same aggregation setting twice. No checker finds this an issue but the calculation core does.

Please check for uniqueness of flow variables in the v2_aggregation table 

### How to Reproduce?

I typed the same aggregation setting twice. No checker finds this an issue but the calculation core does.

Please check for uniqueness of flow variables in the v2_aggregation table 

### What did you expect and what was the actual result?

I typed the same aggregation setting twice. No checker finds this an issue but the calculation core does.

Please check for uniqueness of flow variables in the v2_aggregation table 

### Additional info

Anything else you would like to share?

**Comment by caspervdw** [comment] 2022-11-01 08:06
Duplicate of #202

**Closed by caspervdw** 2022-11-01 08:06 UTC
Labels: enhancement
