### ISSUE TITLE
[Bug]: Python error when running checkers 

### ISSUE THREAD

**Issue by Overmeen** [nens/threedi-modelchecker#170] opened 2022-03-04 14:10 UTC
### Contact Details

stijn.overmeen@nelen-schuurmans.nl

### Complexity

moderate

### Priority

medium prio

### What happened?

ticket: https://nelen-schuurmans.topdesk.net/tas/secure/mango/window/0?t=1646402437864

Python error bij uploaden door fout in timeseries boundary conditions

![image](https://user-images.githubusercontent.com/84539501/156777685-870f2ca5-c311-417d-ac2d-0882e975bd92.png)

### How to Reproduce?

Open calculater.
Press 1,
Press +,
Press 1,
Press =

### What did you expect and what was the actual result?

I expected 2 but the calculator returned 3

### Add screenshots, video's etc

The maximum size for files is 25MB and the maximum size for images is 10MB.

### Additional info

Anything else you would like to share?

**Comment by caspervdw** [comment] 2022-03-08 16:15
Duplicate of #169

**Closed by caspervdw** 2022-03-08 16:15 UTC
Labels: bug
