### ISSUE TITLE
create an overview for users / documentation which checks are performed

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-modelchecker#257] opened 2023-01-05 14:00 UTC
Currently a lot of checks are performed, but it is hard for users, and developers to have an overview of what is currently in the checker

Can we generate an overview that can be used for user documentation?

**Comment by caspervdw** [comment] 2023-02-13 14:47
Duplicate of #279

**Closed by caspervdw** 2023-02-13 14:47 UTC
