### ISSUE TITLE
Schematisation checker: 2 projections

### ISSUE THREAD

**Issue by RichardB9** [nens/threedi-modelchecker#43] opened 2021-02-22 12:51 UTC
@lisannewapstra commented on [Fri Jan 08 2021](https://github.com/nens/ThreeDiToolbox/issues/525)

2101 0057 Wayne 8-1

Wayne used ESPG 28992 (Netherlands) in his global settings on a model in Taiwan
https://api.3di.live/v3.0/threedimodels/14807/

The schematisation checker did not give an error.
The check should be if the raster ESPG and global settings are the same. 

@Jonasvsl

**Comment by RichardB9** [comment] 2021-02-22 12:54
The threedi-modelchecker does not read in external files/raster files. This seems more like an issue for the raster-checker

**Comment by caspervdw** [comment] 2021-09-30 17:38
Duplicate of #69

**Closed by caspervdw** 2021-09-30 17:38 UTC
